In [9]:
import pandas as pd

df = pd.read_csv("weather.csv")
print(df)
type(df)

        day  temperature  windspeed  humidity  event
0  1/1/2017           32          6        20   Rain
1  1/2/2017           35          7        30  Sunny
2  1/3/2017           28          2        45   Snow
3  1/4/2017           24          7        40   Snow
4  1/5/2017           32          4        35   Rain
5  1/6/2017           31          2        20  Sunny

pandas.core.frame.DataFrame

In [10]:
weather_data = [
    ["1/1/2017", 32, 6, 20, "Rain"],
    ["1/2/2017", 35, 7, 30, "Sunny"],
    ["1/3/2017", 28, 2, 45, "Snow"],
    ["1/4/2017", 24, 7, 40, "Snow"],
    ["1/5/2017", 32, 4, 35, "Rain"],
    ["1/6/2017", 31, 2, 20, "Sunny"],
]

df1 = pd.DataFrame(weather_data, columns=["day", "temperature", "windspeed", "humidity", "event"])
df1

        day  temperature  windspeed  humidity  event
0  1/1/2017           32          6        20   Rain
1  1/2/2017           35          7        30  Sunny
2  1/3/2017           28          2        45   Snow
3  1/4/2017           24          7        40   Snow
4  1/5/2017           32          4        35   Rain
5  1/6/2017           31          2        20  Sunny

## Working in Rows and Columns

In [ ]:
print(df.shape) # to get the shape of the table

(6, 5)

In [ ]:
print(df.columns)   # to get all the columns of the table

Index(['day', 'temperature', 'windspeed', 'humidity', 'event'], dtype='object')

In [ ]:
print(df.head())    # to get the first 5 rows of the table

        day  temperature  windspeed  humidity  event
0  1/1/2017           32          6        20   Rain
1  1/2/2017           35          7        30  Sunny
2  1/3/2017           28          2        45   Snow
3  1/4/2017           24          7        40   Snow
4  1/5/2017           32          4        35   Rain

In [ ]:
print(df.head(3))   # to get the first 3 rows of the table

        day  temperature  windspeed  humidity  event
0  1/1/2017           32          6        20   Rain
1  1/2/2017           35          7        30  Sunny
2  1/3/2017           28          2        45   Snow

In [ ]:
print(df.tail())    # to get the last 5 rows of the table

        day  temperature  windspeed  humidity  event
1  1/2/2017           35          7        30  Sunny
2  1/3/2017           28          2        45   Snow
3  1/4/2017           24          7        40   Snow
4  1/5/2017           32          4        35   Rain
5  1/6/2017           31          2        20  Sunny

In [ ]:
print(df.tail(2))   # to get the last 2 rows of the table

        day  temperature  windspeed  humidity  event
4  1/5/2017           32          4        35   Rain
5  1/6/2017           31          2        20  Sunny

In [ ]:
df.sample(3)    # to get any random 3 sample

        day  temperature  windspeed  humidity  event
2  1/3/2017           28          2        45   Snow
5  1/6/2017           31          2        20  Sunny
4  1/5/2017           32          4        35   Rain

In [ ]:
print(df.day)
# print(df["day"])
# print(df.loc[:, "day"])
# print(df.iloc[:, 0])

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [ ]:
print(df[["day", "temperature"]])
# print(df.loc[:, ["day", "temperature"]])
# print(df.iloc[:, [0, 1]])

        day  temperature
0  1/1/2017           32
1  1/2/2017           35
2  1/3/2017           28
3  1/4/2017           24
4  1/5/2017           32
5  1/6/2017           31

In [39]:
df.temperature

0    32
1    35
2    28
3    24
4    32
5    31
Name: temperature, dtype: int64

In [ ]:
df.temperature.describe()   # to get the description of the row

count     6.000000
mean     30.333333
std       3.829708
min      24.000000
25%      28.750000
50%      31.500000
75%      32.000000
max      35.000000
Name: temperature, dtype: float64

In [ ]:
df.temperature.info()   # to get the info of a column

<class 'pandas.core.series.Series'>
RangeIndex: 6 entries, 0 to 5
Series name: temperature
Non-Null Count  Dtype
--------------  -----
6 non-null      int64
dtypes: int64(1)
memory usage: 176.0 bytes

In [ ]:
df.iloc[2, 4]

'Snow'

In [49]:
df.loc[2, "event"]

'Snow'

## Working with operations

In [50]:
df.temperature

0    32
1    35
2    28
3    24
4    32
5    31
Name: temperature, dtype: int64

In [ ]:
df.temperature.max()    # to get the maximum temperature

35

In [53]:
df.temperature.min()    # to get the minimum temperature

24

In [54]:
df.temperature.std()    # to get the standard deviation temperature

3.8297084310253524

In [ ]:
df.temperature.describe()

count     6.000000
mean     30.333333
std       3.829708
min      24.000000
25%      28.750000
50%      31.500000
75%      32.000000
max      35.000000
Name: temperature, dtype: float64

In [58]:
df.temperature == df.temperature.max()

0    False
1     True
2    False
3    False
4    False
5    False
Name: temperature, dtype: bool

In [59]:
df.temperature == df.temperature.min()

0    False
1    False
2    False
3     True
4    False
5    False
Name: temperature, dtype: bool

In [ ]:
df[df.temperature == df.temperature.max()]  # to get the maximum temperature row

        day  temperature  windspeed  humidity  event
1  1/2/2017           35          7        30  Sunny

In [63]:
df[df.temperature == df.temperature.max()].day    # to get the day of maximum temperature

1    1/2/2017
Name: day, dtype: object

In [64]:
df[df.temperature == df.temperature.max()].windspeed    # to get the windspeed of maximum temperature

1    7
Name: windspeed, dtype: int64

In [68]:
df.index  # to get the index

RangeIndex(start=0, stop=6, step=1)

In [69]:
df.set_index("day")     # to set the day column as index

          temperature  windspeed  humidity  event
day
1/1/2017           32          6        20   Rain
1/2/2017           35          7        30  Sunny
1/3/2017           28          2        45   Snow
1/4/2017           24          7        40   Snow
1/5/2017           32          4        35   Rain
1/6/2017           31          2        20  Sunny

In [72]:
df.set_index("day", inplace=True)     # to set the day column as index and modify

In [74]:
df

          temperature  windspeed  humidity  event
day
1/1/2017           32          6        20   Rain
1/2/2017           35          7        30  Sunny
1/3/2017           28          2        45   Snow
1/4/2017           24          7        40   Snow
1/5/2017           32          4        35   Rain
1/6/2017           31          2        20  Sunny

In [75]:
df.reset_index()    # reset to normal indexing

        day  temperature  windspeed  humidity  event
0  1/1/2017           32          6        20   Rain
1  1/2/2017           35          7        30  Sunny
2  1/3/2017           28          2        45   Snow
3  1/4/2017           24          7        40   Snow
4  1/5/2017           32          4        35   Rain
5  1/6/2017           31          2        20  Sunny

In [ ]:
df.sort_values("humidity")  # to sort the data according to humidity in acensending

          temperature  windspeed  humidity  event
day
1/3/2017           28          2        45   Snow
1/4/2017           24          7        40   Snow
1/5/2017           32          4        35   Rain
1/2/2017           35          7        30  Sunny
1/1/2017           32          6        20   Rain
1/6/2017           31          2        20  Sunny

In [ ]:
df.sort_values("humidity", ascending=False)  # to sort the data according to humidity in descending